# .circleci/config.yml file
version: 2.1

jobs:
  build:            # job name
    docker:         # executor type
      - image: camnv2603/udagram-api-feed
      - image: camnv2603/udagram-api-user
      - image: camnv2603/udagram-frontend
      - image: camnv2603/udagram-reverseproxy
    steps:
      - run:
          name: Build and push Docker image
          command: |
            echo "Inside the Build and push Docker image step"
            - docker --version
            - docker build -t udagram-api-feed ./udagram-api-feed
            - docker build -t udagram-api-user ./udagram-api-user
            - docker build -t udagram-frontend ./udagram-frontend
            - docker build -t reverseproxy ./udagram-reverseproxy
            #tagging
            - docker tag udagram-api-feed camnv2603/udagram-api-feed:v1
            - docker tag udagram-api-user camnv2603/udagram-api-user:v1
            - docker tag udagram-frontend camnv2603/udagram-frontend:v1
            - docker tag reverseproxy camnv2603/reverseproxy:v1
            #pushing
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker push camnv2603/udagram-api-feed:v1
            - docker push camnv2603/udagram-api-user:v1
            - docker push camnv2603/udagram-frontend:v1
            - docker push camnv2603/reverseproxy:v1
